### ISSUE TITLE
Humerous "hash" function

### ISSUE THREAD

**Issue by Kaiddd** [arg0NNY/DiscordPlugins#10]
Chief what the FUCK is this

`const hashCode = string => {
                let hash = 0, i, chr;
                if (string.length === 0) return hash;
                for (i = 0; i < string.length; i++) {
                    chr = string.charCodeAt(i);
                    hash = ((hash << 5) - hash) + chr;
                    hash |= 0;
                }
                return hash;
            };`

That is not a hash...... For a script meant to be "security", I expected a lot better.

**Comment by pepper828** [comment]
rofl

**Comment by arg0NNY** [comment]
Fixed in bd8a84376b04a2373d8250c8f4ff1a66377e7a3b
