### ISSUE TITLE
Blank space when turning on fullscreen on video call

### ISSUE THREAD

**Issue by CoolPeachGaming** [arg0NNY/DiscordPlugins#101]
### Plugin:

📜 BetterChannelList

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.1.1

### What client are you using?

🔵 Stable

### Describe the bug

![image](https://github.com/arg0NNY/DiscordPlugins/assets/90976594/1e7bb985-9640-4ccb-bd45-c80caaae6b4a)
Fullscreening a participant in a call results in a blank space on the left, preventing the participant's video from filling up the screen.

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Fixed in d40916cf4b35f93587270604f359911aa6efb205
