### ISSUE TITLE
BetterChannelList does not show anything on most servers

### ISSUE THREAD

**Issue by shinyflvres** [arg0NNY/DiscordPlugins#103]
### Plugin:

⭕ Other/Unrelated

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

 1.1.2 

### What client are you using?

🔵 Stable

### Describe the bug

![grafik](https://github.com/user-attachments/assets/4d78e214-650d-4113-8e94-791294f170e8)

BetterChannelList is not working for me. on some servers it work dunno what i do wrong tbh since theres literally not description about how the plugin works

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
These icons were assigned by Discord's AI, which got shut down at some point, therefore icons are no longer assigned automatically for newly created channels. You can manually set up the icons for each channel locally using context menu on channels.
