### ISSUE TITLE
Crash discord

### ISSUE THREAD

**Issue by AtomiKGamerZ** [arg0NNY/DiscordPlugins#105]
### Plugin:

📜 BetterChannelList

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

better channel list 1.1.3 version

### What client are you using?

🔵 Stable

### Describe the bug

Hello, I have a problem with the "better Channel list" plugin. As soon as I want to modify the icons, it crashes Discord.

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [x] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Fixed in 37781fae6f5c2e8a16820f8ab1ba1a2a46986bf9
