### ISSUE TITLE
Channel list doesn't stay resized

### ISSUE THREAD

**Issue by CoolPeachGaming** [arg0NNY/DiscordPlugins#107]
### Plugin:

📜 BetterChannelList

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.1.4

### What client are you using?

🔵 Stable

### Describe the bug

When manually resizing the channel list, it doesn't stay resized when switching to another channel.

To reproduce, resize the channel list and then click another channel or DM.
![image](https://github.com/user-attachments/assets/ac4965e9-844b-41ec-9e71-818057319d91)
![image](https://github.com/user-attachments/assets/a8124919-1a08-467e-a7ed-8973c1f9c024)

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Fixed in 897efa829008d07639513777568359af8ea3a26f
