### ISSUE TITLE
[PasscodeLock] Option to Disable Animation Effects

### ISSUE THREAD

**Issue by SylveonBottle** [arg0NNY/DiscordPlugins#11]
I suffer from severe motion sickness, need animations disabled everywhere on windows and on discord. The animation for the lockscreen growing/shrinking on screen causes it to act up really bad.

The spinning icon is fine, though. It's just the sudden growing/shrinking black void.

It'd be nice if there was an option to disable this animation. It'd be even nicer if it was synced to discord's "Reduced Motion" setting.

**Comment by lupus0802** [comment]
Hey @SylveonBottle, are you still interested in this feature given you're still using BD?

**Comment by SylveonBottle** [comment]
Considering I went homeless about 7 months ago and had my PC pawned off without my consent, I don't think I use BD anymore.

If anyone else wishes for this feature, feel free to reopen it.

**Comment by lupus0802** [comment]
I’m sorry you’re going through that, I hope your situation will improve soon.
