### ISSUE TITLE
Crash on server view

### ISSUE THREAD

**Issue by hunter-m-git** [arg0NNY/DiscordPlugins#111]
### Plugin:

📜 BetterChannelList

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.1.7

### What client are you using?

🔵 Stable

### Describe the bug

Opening a server causes a discord crash error. no CTD, and works clear when BetterChannelList is disabled.

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by C4J3** [comment]
Copy of Debug.log with error https://pastebin.com/ztWDq5yU

stable 337154 (65fd300) Host 1.0.9166 x64 (53429) Build Override: N/A Windows 11 64-bit (10.0.22631) BD1.10.2 (OpenAsar Nightly f92ee8c also present) BCL 1.1.7

**Comment by kiwishi8** [comment]
have this issue as well.

**Comment by Jomshanseat** [comment]
Same, stopped the crashing when I disabled it after trial and error.
Stable, 1.1.7 on Linux Mint 22 Cinnamon

**Comment by arg0NNY** [comment]
Fixed in cb0a3dd12c50163e1c70f22c8623887a44b31ed2
