### ISSUE TITLE
Unable to open settings using PasscodeLock

### ISSUE THREAD

**Issue by overkill3209** [arg0NNY/DiscordPlugins#115]
### Plugin:

🔒 PasscodeLock

### What version of BetterDiscord are you using?

core v1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

v1.4.12

### What client are you using?

🔵 Stable

### Describe the bug

![image](https://github.com/user-attachments/assets/9cb7ed01-01d4-413a-8a77-c990c624c0cd)

every time i click on the settings icon of the passcode lock plugin i get this error, i have tried disabling everything except the plugin itself and dependencies

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Fixed in 6ee8259aa6d71d4595e555c44539e3dfac15a044
