### ISSUE TITLE
BetterGuildTooltip initializes, but doesn't actually function

### ISSUE THREAD

**Issue by KingGamingYT** [arg0NNY/DiscordPlugins#118]
### Plugin:

📑 BetterGuildTooltip

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.1.1

### What client are you using?

🔵 Stable

### Describe the bug

The plugin will start fine, but it has no actual effect on the server tooltips.
This may be due to discord's shift from i18n to intl language systems and the obfuscation of language strings (assumption).

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Fixed in 94edd34a4de837f332a3486f9e13582fdec21f9e
