### ISSUE TITLE
BetterDiscord Crashing

### ISSUE THREAD

**Issue by SupertytanPL** [arg0NNY/DiscordPlugins#119]
### Plugin:

📜 BetterChannelList

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.1.9

### What client are you using?

🔵 Stable

### Describe the bug

After selecting a discord server, betterdiscord crashes immediately, no crash aftrer disabling the plugin.

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [x] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by samjesus8** [comment]
I am having this issue as well. Whenever I enable this plugin it just crashes my whole Discord
See attached video for what happened

https://github.com/user-attachments/assets/9e6ba29d-d3c2-4a38-947a-8b99287ccd86

**Comment by fowlis** [comment]
Usable error to help:
![Snipaste_2024-11-23_02-32-32](https://github.com/user-attachments/assets/cbb1607c-0165-4ac8-8387-f6588a8ffb6e)

**Comment by arg0NNY** [comment]
Fixed in 00592088246e4e3e693cbdcc785feaeb520889f3
