### ISSUE TITLE
[PasscodeLock]  Ask for passcode upon discord startup

### ISSUE THREAD

**Issue by SylveonBottle** [arg0NNY/DiscordPlugins#12]
Immediately lock the screen upon first initialization of the plugin.

I know we can't do anything until the plugin fully loads, however stopping someone from simply restarting discord is a good start at preventing people from bypassing this locking plugin.

**Comment by arg0NNY** [comment]
Added option in the settings in bd8a84376b04a2373d8250c8f4ff1a66377e7a3b
