### ISSUE TITLE
Crash on preview

### ISSUE THREAD

**Issue by SmolAlli** [arg0NNY/DiscordPlugins#120]
### Plugin:

👀 ChannelsPreview

### What version of BetterDiscord are you using?

1.11.0

### What version of the selected plugin(s) are you using (if applicable)?

2.0.4

### What client are you using?

🔵 Stable

### Describe the bug

Attempting to preview a channel leads to a crash.
![image](https://github.com/user-attachments/assets/d7baf6d7-79af-409e-805e-edfc298b8c30)

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by vapidinfinity** [comment]
just wanted to say this is happening to me as well, for priority's sake
