### ISSUE TITLE
[PasscodeLock] More numbers for more secure locking

### ISSUE THREAD

**Issue by SylveonBottle** [arg0NNY/DiscordPlugins#13]
Allow users to set any number of digits in the passcode. Use [Enter] to confirm.

**Comment by Kaiddd** [comment]
Chief, look at this codes "hash" function, aint any amount of digits gonna protect you with code like this LOL

**Comment by SylveonBottle** [comment]
> Chief, look at this codes "hash" function, aint any amount of digits gonna protect you with code like this LOL

To be fair, someone with any amount of knowledge of this plugin could just.. go to appdata and delete it, restart discord.

**Comment by Kaiddd** [comment]
Very fair point you have here

**Comment by arg0NNY** [comment]
Added in 92d7bc23177846e01874d938b8fdf3373dc69aec
