### ISSUE TITLE
[PasscodeLock] Auto-Lock dropdown menu not showing

### ISSUE THREAD

**Issue by tf2iMicro** [arg0NNY/DiscordPlugins#19]
Before I actually go into details, I'd like to say this is a great mod! Love the idea!

Whenever I click the text, or the little dropdown arrow, the arrow changed directions as if it opens, but it doesn't actually open.
I'd also like to add that sometimes the shortcut doesn't work? I tried to find out why or what triggered it, but couldn't find anything, I'll post a new issue if I do.
While I adress this issue, I'd like to give some advice for future improvements :D (Feel free to ignore them though)
- Have a option to disable button press animations (especially the numbers pressed animation, cause ppl can easier see your password. Maybe have a option to just not have the keypad there to replicate the button presses?)
- AutoLock if you close discord as a window

**Comment by 253ping** [comment]
Dropdown menus not showing is a global BD issue. See #17.

**Comment by arg0NNY** [comment]
Temporarily changed dropdown to radio group in the settings in bd8a84376b04a2373d8250c8f4ff1a66377e7a3b
