### ISSUE TITLE
[ChannelPreview] recent discord update breaks plugin

### ISSUE THREAD

**Issue by elijaholmos** [arg0NNY/DiscordPlugins#2]
hello, excellent plugin idea and great implementation. I love the variety of configuration options.

I recently had a discord update that appeared to break the plugin functionality. here is a screenshot of the JS console and my discord version:
![image](https://user-images.githubusercontent.com/35435704/155825196-06342100-ac7d-474e-bfd2-7cc6577bfbd0.png)
![image](https://user-images.githubusercontent.com/35435704/155825198-f1bbb72f-feec-46c8-a945-72a5cbe15c75.png)

Let me know if I am incorrect about this, or if the issue is indeed on my end.

**Comment by arg0NNY** [comment]
Fixed in 175cf0a341343c6bb7a5783d22cdbff2e46733ad
