### ISSUE TITLE
[PasscodeLock] Set status to AFK while locked.

### ISSUE THREAD

**Issue by 253ping** [arg0NNY/DiscordPlugins#21]
If Discord is locked or autolocked it could change the users status to 'AFK' if the users status was 'Online'.
When the user unlocks Discord the status is reset to the original status.

**Comment by arg0NNY** [comment]
I think this is unnecessary, because you can minimize the Discord, but still be using the computer, then the plugin will autolock Discord and set your status to AFK for you, even if you are not.

Discord has it's own system to set the AFK status and there's no need to modify it.
