### ISSUE TITLE
Lock Discord Icon is placed underneath the close button of voice chat

### ISSUE THREAD

**Issue by Stick-mations** [arg0NNY/DiscordPlugins#28]
![Screenshot 2022-06-16 045652](https://user-images.githubusercontent.com/107615094/174033546-ec4b1203-f78b-4c43-949c-2ce1493357b8.png)

**Comment by arg0NNY** [comment]
Fixed in 74abe57a90e537cb958bea39e1efa24282b028ff

**Comment by Stick-mations** [comment]
nice
