### ISSUE TITLE
[BetterAnimations] (Feature Request) Change animation length(s)?

### ISSUE THREAD

**Issue by rlad78** [arg0NNY/DiscordPlugins#3]
I've got to start off by saying that your plugins are sick and I absolutely love the work you are doing ❤

I recently discovered BetterAnimations and I cannot believe it isn't higher on the BD plugin list. The animations are smooth and surprisingly don't seem to impact my performance at all, from my 3.6GHz quad-core i7 + GTX 1660 SUPER Windows desktop to my 1.0 GHz quad-core i5 Linux laptop. Not sure how much of that is chalked up to Electron optimizations or your programming of the animations, but I am appreciative nonetheless c:

One thing I wish I could change though is the duration of the animations. They look beautiful, but I lean towards liking quicker, snappier animations. It'd be great to be able to change this on a global scale across all animation types, but changing individual animation speeds would be cool too.

If you need any assistance with testing I'd be happy to help out, just let me know!

**Comment by arg0NNY** [comment]
Thanks! Animations duration and easings can be managed through plugin settings.

**Comment by rlad78** [comment]
I...don't know how I didn't see that before. Sorry about that, thanks!
