### ISSUE TITLE
GPU Deactivates itself after some time

### ISSUE THREAD

**Issue by WalEl6512** [arg0NNY/DiscordPlugins#30]
Running the plugin works overall, theres just one Issue. After having the Lock Screen provided from the Plugin, open for too long, the GPU deactivates itself and changes the GPU output or makes the entire PC unfunctional and forces you to hard shutdown.

**Comment by Technetium1** [comment]
You're going to need to phrase that properly. If a GPU deactivates you probably have a broken GPU, or a corrupted OS. The plugin has ***NO EFFECTS*** outside of Discord.

**Comment by arg0NNY** [comment]
@Technetium1 is on point here

**Comment by arg0NNY** [comment]
Closing this, since there have been no updates on this for a long time.
