### ISSUE TITLE
turns off

### ISSUE THREAD

**Issue by ChimkinNuggets** [arg0NNY/DiscordPlugins#31]
after a while the prefix to lock discord stops working and you need to go into your plugins and open settings for it to start working again, is there a way to fix this?

**Comment by arg0NNY** [comment]
Does this problem still exist? If so, could you give me more details about it please.

**Comment by StandingPadAnimations** [comment]
I've noticed this problem too. If you go to the plugin settings, the keybind `Ctrl + L` will work for a little bit but after a while, nothing will happen

**Comment by arg0NNY** [comment]
Most probably fixed in f1e96f99a9a6057df4bff94bbb10fe91c00dd18f. Reopen if the problem still persists.
