### ISSUE TITLE
[InMyVoice] Broken

### ISSUE THREAD

**Issue by Soulivan71** [arg0NNY/DiscordPlugins#32]
Seems to not be display anymore

**Comment by arg0NNY** [comment]
It doesn't seem to be broken for me. Can you screenshot an error in the console please?

**Comment by Soulivan71** [comment]
I have no error

**Comment by Soulivan71** [comment]
I don't know what I can get and its happened only with me finaly

**Comment by Technetium1** [comment]
It's working for me.

**Comment by arg0NNY** [comment]
Closing this issue due to the lack of information about it. Reopen it if you can provide more details on that.

**Comment by Soulivan71** [comment]
![image](https://user-images.githubusercontent.com/36502190/182191380-3cc61bc6-1b14-43ce-b1ad-503842bd630e.png)
![image](https://user-images.githubusercontent.com/36502190/182191571-94492de0-f81d-4440-b7d3-4f11ae6d185c.png)

**Comment by arg0NNY** [comment]
Also seems like you just not in the voice channel. This plugin displays whether the user is in the SAME channel as you, NOT whether he is ANY voice channel.

**Comment by arg0NNY** [comment]
Oh wait, I just realized that it is you on the first two screenshots. Well, the tag is not displaying for you, but only for the others.

**Comment by Soulivan71** [comment]
> Also, by the first two screenshots seems like you're just not in the voice channel. This plugin displays whether the user is in the SAME channel as you, NOT whether he is ANY voice channel.

Before it did

**Comment by 253ping** [comment]
![image-01513](https://user-images.githubusercontent.com/66729859/182205600-08390bb8-e1be-4a39-9b96-4695e893c948.png)
It kinda does. It wont't update the tag as long as you don't switch text channels or hover over the message.
But only if the tag was there before.

**Comment by Soulivan71** [comment]
For me no

**Comment by Soulivan71** [comment]
Still having pb for myself

**Comment by Soulivan71** [comment]
Yeah like I say in my first first message but isn’t display for in the
other chann when before some updates Discord it works before
