### ISSUE TITLE
ChannelsPreview Broken on BBD 1.5.3-Hotfix

### ISSUE THREAD

**Issue by Technetium1** [arg0NNY/DiscordPlugins#34]
First DM to hover on stays previewed with absolute position in top left on top of everything. Shouldn't need a screenshot since it's reproducable, but could provide one if nessecary. This was not happening prior to updating to the Hotfix version.

**Comment by arg0NNY** [comment]
Fixed in 90814bbbe84cb3a294f14f920a53b1186f0cc57e
