### ISSUE TITLE
[ChannelsPreview] Option to preview threads

### ISSUE THREAD

**Issue by LoneDev6** [arg0NNY/DiscordPlugins#35]
Thanks for your awesome plugin, would be really good to also be able to preview threads.

**Comment by TheChilliPL** [comment]
Not sure if I should make another issue for that, but voice chats (with that relatively new chat in voice channels feature) don't seem to be supported either 😅

**Comment by arg0NNY** [comment]
Added support for both in 701d707970998e4900b28ea374fd13e9e3f04b10
