### ISSUE TITLE
[BetterAnimations] Compatibility Request

### ISSUE THREAD

**Issue by adsdawdfawdcwacdaw** [arg0NNY/DiscordPlugins#37]
Plugin does not add animations to FavoriteMedia plugin, if it's possible please make it add the toggle animations from Emoji/Gif/Stickers to the new Image, Video and Audio tabs the plugin provides.

**Comment by arg0NNY** [comment]
It makes no sense because as soon as this plugin changes with some update the updated animations wouldn't work anymore
