### ISSUE TITLE
Where can i create the password?

### ISSUE THREAD

**Issue by GibberishJR** [arg0NNY/DiscordPlugins#39]
Where can i create the password?

**Comment by arg0NNY** [comment]
In the plugin settings.

And please be aware that github issues are related bugs or improvements, not questions. You can ask any question in the support server.

**Comment by GibberishJR** [comment]
> In the plugin settings.
> 
> And please be aware that github issues are related bugs or improvements, not questions. You can ask any question in the support server.

thanks
