### ISSUE TITLE
[PasscodeLock] Could not open settings

### ISSUE THREAD

**Issue by 0xspade** [arg0NNY/DiscordPlugins#46]
the title says it all. Installed the latest version, Can't open the gear icon, and it says "Could not open settings"

**Comment by arg0NNY** [comment]
What version have you installed?

**Comment by 0xspade** [comment]
Hi @arg0NNY,

Thanks for the quick reply. Luckily, after some few restart it enables it. Just want to suggest another feature if you don't mind?

scramble the num pad on lock screen or an option to disable the num pad.

**Comment by arg0NNY** [comment]
Good. Write your suggestion in a separate issue please.
