### ISSUE TITLE
[BetterAnimations] Plugin could not be compiled.

### ISSUE THREAD

**Issue by Orangenal-name** [arg0NNY/DiscordPlugins#50]
When adding the plugin, I just get this error: 
![image](https://user-images.githubusercontent.com/44399774/195691858-1b536db9-827d-41e5-a7ff-74f619bb926d.png)

**Comment by weirdal3333** [comment]
I can confirm that this is an issue with the latest commit, and not betterdiscord. 1.1.9 still works as expected on the latest versions of discord and betterdiscord.

**Comment by arg0NNY** [comment]
The error on the screenshot couldn't have happened in 1.1.10, that's definitely an older version

**Comment by arg0NNY** [comment]
@weirdal3333 can you screenshot an error that you're getting with 1.1.10 please?
