### ISSUE TITLE
sometimes after only one bad code the plugin locks you out for 25 seconds

### ISSUE THREAD

**Issue by jack652** [arg0NNY/DiscordPlugins#54]
sometimes after only one bad code the plugin locks you out for 25 seconds

**Comment by arg0NNY** [comment]
Can you please provide more info on that? What actions are needed to reproduce this? Are you sure that you didn't input invalid code before? (Including the cases where you restarted the Discord after inputting invalid code)

**Comment by arg0NNY** [comment]
Closed due to inactivity.
