### ISSUE TITLE
BetterAnimation Animation Type doesnt show up as an option

### ISSUE THREAD

**Issue by tetralovania** [arg0NNY/DiscordPlugins#58]
![image](https://user-images.githubusercontent.com/86831655/204096610-cb1bd275-f19a-42ab-881d-c9e212e52d6c.png)

**Comment by arg0NNY** [comment]
This is _Zere's Plugin Library_ issue, download the fixed version from the [support server](https://discord.gg/M8DBtcZjXD) and use it until the official fix comes out.
