### ISSUE TITLE
[Bugs&Animations] A small glitch with channel animations

### ISSUE THREAD

**Issue by DrFontanez** [arg0NNY/DiscordPlugins#6]
When I was playing channel animations with streamer mode enabled, the channel animation will be a little glitchy. 

The start position between first animation and second animation are different. Here shows the video.

https://user-images.githubusercontent.com/91207879/162246268-b1f6bc8b-ee71-4fd4-bd7b-520b5c734fd0.mp4

**Comment by arg0NNY** [comment]
Fixed in f9eb84a4f4832ca9a74ebd1ae5835c0589c2e081
