### ISSUE TITLE
BetterAnimations prevents pasting into the chat box

### ISSUE THREAD

**Issue by mmcmd** [arg0NNY/DiscordPlugins#61]
Whenever the plugin is enabled, the "Paste" button in the right click menu of the Discord chatbox does not work and does not paste your clipboard into the chatbox.

Pressing the Ctrl-V combination works however

![Image](https://i.imgur.com/D2jrDwk.gif)

**Comment by lupus0802** [comment]
Is this still an issue? Are you sure BetterAnimations is causing it?

**Comment by mmcmd** [comment]
sorry, havent used betterdiscord in a couple months so I couldn't tell you

**Comment by lupus0802** [comment]
Alright, I will close this as resolved, please create a new issue if you encounter this again.
