### ISSUE TITLE
there is no other options

### ISSUE THREAD

**Issue by peter-ux** [arg0NNY/DiscordPlugins#62]
![image](https://user-images.githubusercontent.com/56302350/214307106-8186ccb6-a05a-4d6a-9d4e-81e679f2f09c.png)

**Comment by lupus0802** [comment]
This is a current bug with ZeresPluginLibrary. The developers of the library will have to solve the problem, however, we're working on a temporary fix.

**Comment by arg0NNY** [comment]
This is _Zere's Plugin Library_ issue, download the fixed version from the [support server](https://discord.gg/M8DBtcZjXD) and use it until the official fix comes out.
