### ISSUE TITLE
[BetterGuildTooltip] getDefaultChannelForGuild is not a function

### ISSUE THREAD

**Issue by fowlis** [arg0NNY/DiscordPlugins#63]
Console produces this error when hovering over server icons and the extra tooltip details don't show on the servers it produces this error on
![Snipaste_2023-02-09_11-30-52](https://user-images.githubusercontent.com/84232621/217801063-a90d226f-bd30-4c1e-b877-e73f215c2e9a.png)

**Comment by arg0NNY** [comment]
Fixed in 387cb313c6e900ccfd1c9b17a9ab0230d5e59a50
