### ISSUE TITLE
No preview popups appear but the background doesn't darken

### ISSUE THREAD

**Issue by sbeve72** [arg0NNY/DiscordPlugins#64]
When I hover over another channel, no preview pops up but the current channel does darken (as it should). I have tried fiddling around with settings, nothing fixed it. I even tried reinstalling the plugin/restarting Discord.

**Comment by lupus0802** [comment]
The ChannelsPreview plug-in is currently broken, we're working on a fix.

**Comment by arg0NNY** [comment]
This is Zere's Plugin Library issue, wait for their updates.
