### ISSUE TITLE
Crashing Discord

### ISSUE THREAD

**Issue by angsaysroar** [arg0NNY/DiscordPlugins#65]
The plugin started causing Discord to crash. I'm not sure why, but even after removing it entirely from the plugins folder and reinstalling it, the issue persists.

I would greatly appreciate it if this plugin could be updated because it is one that has been really beneficial to many users.

I took a look at BetterDiscord debug logs and found this:

> [2023-03-01 02:38:41.729][CONSOLE:INFO] [PasscodeLock] version 1.4.1 has stopped.
> [2023-03-01 02:38:41.731][CONSOLE:LOG] updateVideoQuality: {
>     "remoteSinkWantsMaxFramerate": 30
> }
> [2023-03-01 02:38:41.889][CONSOLE:LOG] updateVideoQuality: {
>     "remoteSinkWantsMaxFramerate": 30
> }
> [2023-03-01 02:38:46.265][CONSOLE:WARN] Window state not initialized window-1

**Comment by arg0NNY** [comment]
Fixed in 76e2cb88d6fc09843532b91fecad7344356c04f5
