### ISSUE TITLE
BetterAnimations crashes whenever someone else sends a message

### ISSUE THREAD

**Issue by OnlyCS** [arg0NNY/DiscordPlugins#66]

**Comment by lupus0802** [comment]
Does the issue still occur - I can't reproduce the problem.

**Comment by OnlyCS** [comment]
yes, even turning off the plugin fixed the issue

**Comment by lupus0802** [comment]
Can you try with the latest version of the plugin?

**Comment by lupus0802** [comment]
I'll mark this as fixed due to inactivity.
