### ISSUE TITLE
BetterAnimations, BetterGuildTooltip and ChannelsPreview Localization

### ISSUE THREAD

**Issue by panos78** [arg0NNY/DiscordPlugins#69]
About BetterAnimations, I have translated the plugin in Greek into CrowdIn but I don't see it active.
Should I do something else?

About BetterGuildTooltip and ChannelsPreview, can we localize the Settings window?

**Comment by arg0NNY** [comment]
No more action is required from you regarding BetterAnimations. Trainslation will be included in the future versions.

ChannelsPreview localization can be done here: https://crowdin.com/project/betterdiscord-channelspreview

Localiztion of BetterGuildTooltip plugin hasn't started yet.
