### ISSUE TITLE
a shift

### ISSUE THREAD

**Issue by Bonbon42** [arg0NNY/DiscordPlugins#70]
During the animation between two channels, there is a shift.
I think it's due of my theme "Spectra".

https://user-images.githubusercontent.com/99346056/235383205-ce21b013-6cec-4157-9985-5577c35e86d4.mp4

**Comment by lupus0802** [comment]
I assume you mean that the channel box slightly moves to the right when switching channels.
Have you tried without the theme enabled?

**Comment by Bonbon42** [comment]
yes and it work without.

**Comment by lupus0802** [comment]
Then this might be a won't fox case, nevertheless, I'll let argonny comment on it.
