### ISSUE TITLE
[BetterGuildTooltip] Crash after activation

### ISSUE THREAD

**Issue by BySwiizen** [arg0NNY/DiscordPlugins#77]
Since the last Discord update, the plugin crashes all the time. Can you fix it please?

**Comment by lupus0802** [comment]
Discord pushed an update that broke all plugins and also BD itself. BetterDiscord fixed the core a few hours ago, arg0nny is currently working on fixing plugins from this repo.

**Comment by lupus0802** [comment]
This issue has been fixed in the latest release. If you don't get a prompt to update automatically via ZeresPluginLibrary, please download the plugin manually.
