### ISSUE TITLE
Mouse Clicking on Screen Numbers Doesn't Work if the Password was Set with Numpad Numbers

### ISSUE THREAD

**Issue by DaRootBeer1231** [arg0NNY/DiscordPlugins#78]
Set my password with the numpad and when I tried to input the password with the mouse by clicking the on screen numpad, it didn't work. I don't know if this is a bug or intentional.

**Comment by lupus0802** [comment]
I assume you're talking about the on-screen buttons when Discord is locked? If not, please clarify. If yes, we can't reproduce the issue, please give us more information, such as your BD version as well as version of the PasscodeLock version. Other than that, please try to disable other plugins/themes to verify that the issue is occurring in because of PasscodeLock.

**Comment by DaRootBeer1231** [comment]
Yes the on screen buttons. So I set my password using the numpad (example, 1234), but if I try to input the password using the on-screen buttons by clicking them with the mouse then it doesn't unlock. My Better Discord version is 1.9.5 and my PasscodeLock is 1.4.4. I disabled everything except PasscodeLock and it still wasn't working. I'm not sure if that's how it's meant to be or if it's a bug. Sorry for not being more descriptive.

**Comment by lupus0802** [comment]
Are you referring to the on-screen buttons when setting a passcode or when actually unlocking the app? It shouldn't really make a difference how you originally set the passcode because the storage method is the same. The on-screen buttons work fine for us when unlocking Discord.

**Comment by DaRootBeer1231** [comment]
When unlocking it. It's defiantly not working for me because when I change my password to be set using the numbers at the top of the keyboard, then input my password using the on-screen buttons, it unlocks. But it doesn't work when it was set using the numpad.

**Comment by lupus0802** [comment]
So to confirm:
Setting password with the top number "row" or on-screen buttons, then unlocking with on-screen buttons or numpad => Works

Setting password with numpad
-> Using the on-screen buttons or number row => Doesn't work
-> Using the numpad => Works

Is that correct?

**Comment by DaRootBeer1231** [comment]
Holy crap I just realized how stupid I am. The numpad on screen is upside-down from the one on my keyboard and I was hitting it wrong this whole time without realizing it. I don't even have words for how dumb I feel. Have a nice day.

**Comment by lupus0802** [comment]
Mystery solved :D 
Thank you for notifying us, have a nice day!
