### ISSUE TITLE
Dev tools issue

### ISSUE THREAD

**Issue by hexkiller78** [arg0NNY/DiscordPlugins#8]
Can remove the passcode by opening the Developer Tools and inspects elements.

**Comment by Kaiddd** [comment]
yes, ctrl+shift+i entirely defeats this plugin, I was laughing so hard

**Comment by arg0NNY** [comment]
Yeah, you should disable devtools in the BetterDiscord settings

**Comment by Kaiddd** [comment]
@arg0NNY or, you could edit discord to fully not work till a passcode is entered, sure this could be bypassed too but it'd be a lot harder than just deleting an element and then disabling the plugin!

**Comment by arg0NNY** [comment]
Fixed in bd8a84376b04a2373d8250c8f4ff1a66377e7a3b

**Comment by arg0NNY** [comment]
Fixed in 92d7bc23177846e01874d938b8fdf3373dc69aec
