### ISSUE TITLE
Plugin Issues

### ISSUE THREAD

**Issue by Lagomorpheus** [arg0NNY/DiscordPlugins#80]
### Plugin:

🔒 PasscodeLock, 📜 BetterChannelList

### What version of BetterDiscord are you using?

1.9.6

### What version of the selected plugin(s) are you using (if applicable)?

CL 1.0.2 PL 1.4.5

### What client are you using?

🔵 Stable

### Describe the bug

ChannelList: Emojis for channel lists stopped working today. 
![image](https://github.com/arg0NNY/DiscordPlugins/assets/120220827/c40112ef-6e51-426f-aba5-b3aa53dadc5f)

PasscodeLock: When discord loads up, crashes or restarts the lock screen does not initialize, forcing me to go into plugins, scroll down and disable and reenable it. (Possibly related, discord will randomly close with no crash pop up and will continue doing so until PC restarts, even on a version of discord where BD has been uninstalled, this has only happened to me while using passcode lock and streaming)

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by lupus0802** [comment]
Hey, thanks for reporting. I assume you recently updated Discord?

**Comment by Lagomorpheus** [comment]
When I go to sleep I turn my PC off completely, I assume discord did a ghost update overnight and caused these issues?

**Comment by lupus0802** [comment]
The issue has been fixed in the newest version of the plugins (1.0.3/1.4.6), the library plugin should prompt you to update. If it doesn't, you may need to download the plugins manually.
