### ISSUE TITLE
Thinner channel options

### ISSUE THREAD

**Issue by QuentinMcCarthy** [arg0NNY/DiscordPlugins#83]
### Plugin:

📜 BetterChannelList

### Suggestion:

The channel list becomes quite bloated when using all the options, however I like the redesign and having the last sent message in the list. Would it be possible to have an option to debloat the list? i.e. make each channel appear thinner?

I've already gone into the custom CSS and reduced the size of the icons which has helped massively in particular with the voice channels, but the text channels are still quite bloated.

**Comment by arg0NNY** [comment]
Different icon sizes implemented in c1250237ccb5aa7076bd5a93c71f1b12b5c1a302
