### ISSUE TITLE
cannot click any buttons, channels or members after BetterChannelList finished loading and displays the last message from every channel in the server

### ISSUE THREAD

**Issue by jack652** [arg0NNY/DiscordPlugins#84]
### Plugin:

📜 BetterChannelList

### What version of BetterDiscord are you using?

core v1.9.7

### What version of the selected plugin(s) are you using (if applicable)?

v1.0.4

### What client are you using?

🔵 Stable

### Describe the bug

after BetterChannelList finished loading and displays the last message from every channel in the server, I suddenly cannot click any buttons, channels or members anymores
I can open my settings, but after it opens, I once again cannot click any buttons there, including the close button (the escape key also does not work anymore)

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by sirlupusdev** [comment]
I can't reproduce this issue. Do you have access to the console so you could check if any errors appear?

**Comment by arg0NNY** [comment]
Closed due to inactivity from author. Re-open if the problem still occurs.
