### ISSUE TITLE
Server-Emojis in Channel list are shown as their name (alt text/ "emoji") instead of emoji

### ISSUE THREAD

**Issue by ojsef39** [arg0NNY/DiscordPlugins#85]
### Plugin:

📜 BetterChannelList

### What version of BetterDiscord are you using?

1.9.7

### What version of the selected plugin(s) are you using (if applicable)?

1.0.4

### What client are you using?

🔵 Stable

### Describe the bug

Hi thanks for the plugin!

I found this issue when i installed the plugin, and i think this screenshot shows it the best:
<img width="623" alt="image" src="https://github.com/arg0NNY/DiscordPlugins/assets/43563019/07f30cc3-487b-4d06-8d21-05ddf3cc5935">

Custom server emojis (or generally discord emojis) are not shown as channel icons, instead the plugin shows the name of the emoji, which looks unfortunate. This happens across all servers i use.

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [ ] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Can you please provide any server where this issue occurs?

**Comment by ojsef39** [comment]
> Can you please provide any server where this issue occurs?

It happens on all servers for me, but here is a link to one: https://discord.gg/lo-cafe

**Comment by sirlupusdev** [comment]
I'm able to reproduce the issue with some servers of mine, we'll investigate this.

**Comment by ojsef39** [comment]
Hope, #87 resolves it. Thanks for your effort! :)
