### ISSUE TITLE
[Better Channel Previews] Blank Previews

### ISSUE THREAD

**Issue by TaktischerSpeck** [arg0NNY/DiscordPlugins#89]
### Plugin:

👀 ChannelsPreview

### What version of BetterDiscord are you using?

1.10.1

### What version of the selected plugin(s) are you using (if applicable)?

1.4.3

### What client are you using?

🔵 Stable

### Describe the bug

When I mouse over a channel or chat the background is changing the colour but nothing else happens.

![Discord_edpzI9BSk6](https://github.com/arg0NNY/DiscordPlugins/assets/29396439/54b77d66-0bce-4f52-b660-a437e8701766)

### Additional comments

I tried reinstalling BetterDiscord, disabling all plugins, deleting and downloading the plugin from GitHub.

```md
## Discord Info
stable 292725 (485a03a) Host 1.0.9146 x64 (47543) Windows 11 64-bit (10.0.22631)

## BetterDiscord
stable 1.10.1

### Plugins (1 Enabled):
- AppNotifications
- AutoIdleOnAFK
- BDFDB
- BetterFormattingRedux
- BetterRoleColors
- BugReportHelper
- ChannelsPreview (Enabled)
- CompleteTimestamps
- CustomStatusPresets
- Double Click To Edit
- FileViewer
- GameActivityToggle
- InvisibleTyping
- MessageLoggerV2
- PluginRepo
- PreviewMessage
- QuickMention
- ReadAllNotificationsButton
- ShowHiddenChannels
- SplitLargeMessages
- XenoLib
- ZeresPluginLibrary

### Themes (0 Enabled):

```

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Fixed in d8520cdb31980b846eb643c31afd90d0fe8bf689
