### ISSUE TITLE
Passcode stuff

### ISSUE THREAD

**Issue by SylveonBottle** [arg0NNY/DiscordPlugins#9]
-option to disable the animation effects (I have reduced motion enabled for a reason)
-automatically lock discord upon starting the client (so no one can just restart discord to bypass)
-allow users to have more digits in their passcode
-allow letters in passcode?
-disable notifications from client when locked

lmk if you want these in seperate issues

**Comment by arg0NNY** [comment]
Yes, it would be nice to separate it, since it is unlikely that I will add all of this in one update. Thanks.

**Comment by SylveonBottle** [comment]
Moved to separate tickets.
