### ISSUE TITLE
issue with the plugin

### ISSUE THREAD

**Issue by angrybirdice** [arg0NNY/DiscordPlugins#95]
### Plugin:

⭕ Other/Unrelated

### What version of BetterDiscord are you using?

v1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

v1.1.19

### What client are you using?

🔵 Stable

### Describe the bug

unable to use or enable the plugin due to errors within the module due to roblox update
![bandicam 2024-06-19 23-29-15-102](https://github.com/arg0NNY/DiscordPlugins/assets/39227462/04ede915-e663-4921-b4ae-12e9d53f5f78)

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Download the [latest version](https://arg0nny.github.io/bd/download/?id=BetterAnimations).
