### ISSUE TITLE
ChannelsPreview could not be compiled

### ISSUE THREAD

**Issue by Pharaoh2k** [arg0NNY/DiscordPlugins#98]
### Plugin:

👀 ChannelsPreview

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.4.3

### What client are you using?

🔵 Stable

### Describe the bug

ChannelsPreview could not be compiled ever since the new discord update

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Fixed in d8520cdb31980b846eb643c31afd90d0fe8bf689
